id: A0AF450F4
title: 'Fostering Recollection to Dispel the Torment of Deluded Perception: An Aspiration
  for the Bardos'
type: translation
pechas:
- I54A3D52A
- I2454B5C7
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:07:10.226222
  last_modified_at: 2023-01-04 12:07:10.226237
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I54A3D52A/F465: 3C8B
  I2454B5C7/FA2F: 3C8B
